// Mocks generated by Mockito 5.3.2 from annotations
// in messaging/test/units/queue_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:messaging/src/queues/message_queue.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MessageQueueDispatcher].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageQueueDispatcher extends _i1.Mock
    implements _i2.MessageQueueDispatcher {
  MockMessageQueueDispatcher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void dispatch(String? item) => super.noSuchMethod(
        Invocation.method(
          #dispatch,
          [item],
        ),
        returnValueForMissingStub: null,
      );
}
